### ISSUE TITLE
SQL Based: XSLT transformation success from integration account having more logs instead of success run

### ISSUE THREAD

**Issue by vgouth** [Azure/logicapps#1199]
### Describe the Bug with repro steps 

\*\*Prerequisites: \*\* 

 1\.Create an integration account or use existing integration account which is one time setup. Select the pricing tier as standard. 

 a) To link integration account to logic app.

 a) In integration account's navigation menu, under Settings, select Callback URL.Find the Generated Callback URL property value, copy the value, and save the URL to use later for linking.

 On your logic app's navigation menu, under Settings, select Environment variables.On the Environment variables page, check whether the app setting named WORKFLOW\_INTEGRATION\_ACCOUNT\_CALLBACK\_URL exists.

 If the app setting doesn't exist, at the end of the settings list, add a new app setting by entering the following:

 "WORKFLOW\_INTEGRATION\_ACCOUNT\_CALLBACK\_URL":""

 b) In the Logic App, navigate to Artifacts > Maps, click on "Add", and upload a XSLT map. 

 c) In the Integration account, navigate to Settings > Maps, click on "Add", and upload a XSLT map.

 2\.Open the designer and incorporate an HTTP request trigger.

3. Insert an Transform XMl action. 
4. For the content you wish to validate, add the code ()(add without brackets). 
5. Set the Maps Source to Logic App. 
6. For the Map Name, select the XSLT map that has been uploaded to the Logic App. 
7. Implement a Response action with a status code of 200. For the body, use the "Transformed XMl output" token from the Transform XMl action. 
8. Save the workflow. 
9. Launch Postman. 
10. Choose "Post" and input the workflow runtime URL. Press send. 

**Expected:**Run should get success in the run history.

**Actual:** Run in the run history is in running state and there are some logs present.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/3e5343be-01c7-4d7a-96fc-4de51af907ce>)

![Image](<https://github.com/user-attachments/assets/afd66527-dbd3-4969-9feb-dcef195786d3>)

**Logs:**

[2024-10-09T12:45:00.192Z] Job error: correlationId='235186b2-6cab-4ebc-8d5f-1e4a9d2d109c', operationName='XsltActionJob.ExecuteAction', jobPartition='AEBD9F620F854862A7DE528FDF8F3365:2D08584731289912163486663915045CU00', jobId='08584731289912163486663915045CU00', message='XsltActionJob failed with unexpected exception.', exception='System.InvalidCastException: Unable to cast object of type 'Microsoft.Azure.Workflows.Data.Configuration.EdgeFlowSqlDataProviders' to type 'Microsoft.Azure.Workflows.Integration.Configuration.IntegrationAccountFlowDataProviders'.

 [2024-10-09T12:45:00.195Z] at Microsoft.Azure.Workflows.Integration.Extensions.IFlowConfigurationHolderExtensions.GetIntegrationAccountFlowDataProviders(IFlowConfigurationHolder holder)

 [2024-10-09T12:45:00.198Z] at Microsoft.Azure.Workflows.Integration.Extensions.IFlowConfigurationHolderExtensions.GetIntegrationAccountDataProvider(IFlowConfigurationHolder holder, IntegrationAccountInformation integrationAccount)

 [2024-10-09T12:45:00.205Z] at Microsoft.Azure.Workflows.Worker.Jobs.XsltActionJob.GetMapContentLink(ArtifactInformation map)

 [2024-10-09T12:45:00.208Z] at Microsoft.Azure.Workflows.Worker.Jobs.XsltActionJob.ExecuteAction(FlowRunActionExecutionContext actionExecutionContext)', organizationId='', activityVector='IN.03', additionalProperties='{"ParentActivityId":"00-51c7bbcd25d8d2bcf2e3e7b2d2422071-2a8b6c60e5e57af6-00"}', extensionVersion='1.94.1.0', siteName='UNDEFINED\_SITE\_NAME', slotName='', activityId='3e2431a1-61b1-4c0f-ab39-77bdb33e292e'.

### Browser 

VS Code

### Additional context 

**VSIX Version:** 4\.96.0

**Comment by vgouth** [comment]
Issue repro in the latest VS Code request

**VSIX Version:** 4.107.0
![Image](https://github.com/user-attachments/assets/9610372e-6c8f-4d4f-8ab2-a008e08ec06b)

**Comment by vgouth** [comment]
Issue repro in the latest VS Code request

**VSIX Version:** 4.116.7-fixSessions

**Comment by vgouth** [comment]
It is in progress

**Comment by vgouth** [comment]
Issue repro in latest build
**VSIX Version:**5.14.2

**Comment by vgouth** [comment]
Issue repro in latest build
**VSIX Version:** 5.18.5

**Comment by vgouth** [comment]
Issue repro in latest bundle release test pass. 
**VSIX Version :** 5.18.7

**Comment by vgouth** [comment]
Issue repro in latest VS code test pass
VSIX version : 5.44.5

**Comment by vgouth** [comment]
Issue repro in latest VS code test pass
**VSIX version :** 5.58.4

**Comment by vgouth** [comment]
Issue repro in latest VS code test pass.
**VSIX Version:** 5.94.0

**Comment by vgouth** [comment]
Issue repro in latest production VS code test pass.
**VSIX Version:** 5.94.17

![Image](https://github.com/user-attachments/assets/71bba750-7049-4da6-85a3-dd91197cff50)

**Comment by vgouth** [comment]
Issue repro in latest VS code test pass.
**VSIX Version:** 5.109.13

**Comment by vgouth** [comment]
Issue repro in latest VS code test pass.
**VSIX Version:** 5.117.3
