### ISSUE TITLE
Function host is not running when running as container

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#123]
I'm going through the [Run as Docker container](https://github.com/Azure/logicapps/wiki/4.-Deploy-to-a-Docker-container) steps and get the following response when calling it via REST:
> Function host is not running.

Logs of the container itself are:
> Starting OpenBSD Secure Shell server: sshd.
> Hosting environment: Production
> Content root path: /
> Now listening on: http://[::]:80
> Application started. Press Ctrl+C to shut down.

Happy to give access to the private GitHub repo.

**Comment by tomkerkhove** [comment]
I've invited you to the repo and should be able to reproduce by following the README.

**Comment by tomkerkhove** [comment]
Dropped you a note offline to help with troubleshooting.

**Comment by shankarmaha** [comment]
@tomkerkhove Did you got around this issue? I am also getting the same error.

**Comment by tomkerkhove** [comment]
Unfortunately not

**Comment by shankarmaha** [comment]
I added the below in the docker file and I can now see that the function host is started

ENV AZURE_FUNCTIONS_ENVIRONMENT Development 

However, I get a unauthorized when calling the URL. Will keep digging

**Comment by tomkerkhove** [comment]
That did the trick for me, thanks!

For unauthed exceptions, make sure to use the correct master key (see [wiki](https://github.com/Azure/logicapps/wiki/4.-Deploy-to-a-Docker-container))

**Comment by shankarmaha** [comment]
That's the bit, I don't get it. 

On the dockerfile, I set the connection string for my storage account

ENV AzureWebJobsStorage <storage account connection string>

I assume the master key is the same as the  Key found under Storage account > keys

![image](https://user-images.githubusercontent.com/4720931/84662353-9fe44c80-af13-11ea-939f-5256692b1c9f.png)

Appreciate if you could help me on this

**Comment by tomkerkhove** [comment]
It is not, see the wiki above for more details:
> To obtain the Master_Key value, see details at Azure/azure-functions-docker/issues/84, but to summarize:
> 
> The master-key is defined in the storage account you have set for AzureWebJobsStroage in azure-webjobs-secrets/{deployment-name}/host.json It should look something like this:
> 
> { ... "masterKey": { "name": "master", "value": "{value in here}", "encrypted": false } ... }

**Comment by shankarmaha** [comment]
Thanks @tomkerkhove. I can now find the master key. Unfortunately, I am getting another error now

Error message: subscriptionId='myedgeenvironment', correlationId='36319478-2a30-4214-9045-19c97d1bab81', principalOid='', principalPuid='(null)', tenantId='myedgeenvironment-tenantId', operationName='POST/RUNTIME/FLOW/MANAGEMENT/LOGICAPPSV2/MANUAL/', message='Http request failed with unhandled exception of type 'NullReferenceException' and message: 'System.NullReferenceException: Object reference not set to an instance of an object.

at Microsoft.Azure.Workflows.Data.Engines.FlowUriTemplateEngine.GetRelativePathTriggerDirectApiUri(Uri endpoint, String apiVersion, String scaleUnit, String flowId, String flowName, String triggerName)

at Microsoft.Azure.Workflows.Data.Definitions.CallbackUrlDefinition.GetTriggerCallbackUrlDefinition(Uri endpoint, String apiVersion, FlowAccessKey flowAccessKey, AccessKeyType keyType, Flow flow, String triggerName, String relativePath, FlowHttpMethod triggerHttpMethod, Nullable`1 expirationTime, String flowSequenceId)

at Microsoft.Azure.Workflows.Web.Common.RequestHandlers.FlowTriggerApiRequestHandler.GetCallbackUrl(FlowContext context, String flowVersion, String triggerName)

at Microsoft.Azure.Workflows.Web.Controllers.EdgeFlowTriggerController.ListCallbackUrl(String flowName, String triggerName, CancellationToken cancellationToken)

at Microsoft.Azure.Workflows.Web.FlowExtensionRouteInitializer.Invoke(HttpRequestMessage request, CancellationToken cancellationToken)

at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionHttpRequestHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)

at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionRequestCancellationHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)

at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionAuthorizationHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)

at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionErrorResponseHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)'.', exception='System.NullReferenceException: Object reference not set to an instance of an object.

at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionErrorResponseHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)', organizationId='(null)', activityVector='IN.06', realPuid='', altSecId='', additionalProperties='(null)'.

Have you seen this error?

**Comment by tomkerkhove** [comment]
Yes, see #129

**Comment by laveeshb** [comment]
@shankarmaha @tomkerkhove -- we are aware of the NRE issue when loading a workflow with request or recurrence trigger when running in a container. I am investigating it.
In the meantime, to get unblocked, you can test your scenarios by running the same workflow outside a container.

**Comment by tomkerkhove** [comment]
Thanks for the update!

**Comment by tomkerkhove** [comment]
Any update on this? It's blocking us a bit to proceed on our end.

**Comment by tomkerkhove** [comment]
> I added the below in the docker file and I can now see that the function host is started
> 
> ENV AZURE_FUNCTIONS_ENVIRONMENT Development

Actually I'm re-opening this as it's not documented yet AFAIK

**Comment by Roshan456** [comment]
@tomkerkhove 
Hi , I am getting the below issue while run logic app as docker container on local machine.

Host.Triggers.Workflows[801]
      Workflow Error: operationName='FlowDefinitionProvider.GetFunctionMetadataAsync', message='Workflow 'SQLTestWF' is not valid, skipping function metadata injection.', exception='(null)'

**Comment by tomkerkhove** [comment]
That I don't know, sorry!

**Comment by Roshan456** [comment]
@laveeshb 
Hi , I am getting the below issue while run logic app as docker container on local machine.
I have followed the steps mentioned in the article.

Host.Triggers.Workflows[801]
Workflow Error: operationName='FlowDefinitionProvider.GetFunctionMetadataAsync', message='Workflow 'SQLTestWF' is not valid, skipping function metadata injection.', exception='(null)'

**Comment by rohithah** [comment]
@Roshan456 - do you see any other error messages - if not would you be able to share the workflow.json file content from SQLTestWF?

**Comment by Roshan456** [comment]
@rohithah I was able to solve this error by adding right environment variables.

**Comment by rohithah** [comment]
closing this since we moved the documentation to docs.microsoft.com with the feedback from this thread

**Comment by namrathah7** [comment]
can you please share the host.json file..i get no functions loaded error when i run the container
