### ISSUE TITLE
SAP built-in connector does not trigger when receiving 15MB messages.

### ISSUE THREAD

**Issue by poeloeloe** [Azure/logicapps#1250]
### Describe the Bug

We ran into an issue with the built-in SAP connector where we can't receive large messages using the "When a message is received from SAP" trigger.

The message in question is about 15MB in size, according to all the docs messages up to 100MB should be supported.

We are seeing this error message in the NCO RFC logs:
```
SAP.Middleware.Connector.RfcServerApplicationException: Uncaught exception SAP.Middleware.Connector.RfcAbapException thrown in Microsoft.Azure.Workflows.ServiceProviders.Sap.NetFx.Server.ServerCallbackHandler.CallbackFunction when executing RFC server function Z_TEST_MESSAGE ---> SAP.Middleware.Connector.RfcAbapException: RpcException: Received message exceeds the maximum configured message size.
   at Microsoft.Azure.Workflows.ServiceProviders.Sap.NetFx.Utility.BapiReturnUtility.FindAndSetReturn(IRfcFunction function, RfcAbapBaseException rfcErrorResponseException, RfcServerContext rfcServerContext) in C:\__w\1\s\src\functionWorkers\serviceProviders\ServiceProviders.Sap.NetFx\Utility\BapiReturnUtility.cs:line 93
   at Microsoft.Azure.Workflows.ServiceProviders.Sap.NetFx.Server.ServerCallbackHandler.CallbackFunction(RfcServerContext context, IRfcFunction function) in C:\__w\1\s\src\functionWorkers\serviceProviders\ServiceProviders.Sap.NetFx\Server\ServerCallbackHandler.cs:line 138
   at SAP.Middleware.Connector.RfcServer.InvokeServerFunction(RfcConnection conn, ServerFunctionInfo serverFuncInfo, RfcServerFunction functionImp)
   --- End of inner exception stack trace ---
   at SAP.Middleware.Connector.RfcServer.InvokeServerFunction(RfcConnection conn, ServerFunctionInfo serverFuncInfo, RfcServerFunction functionImp)
   at SAP.Middleware.Connector.RfcServer.Dispatch(RfcConnection conn)
   at SAP.Middleware.Connector.RfcConnection.Dispatch()
   at SAP.Middleware.Connector.RfcConnection.RfcServerWorkerThreadProc(Object rfcConnObj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Upon investigating this issue it seems that there might be some kind of GRPC communication taking place between the netfx worker (that runs the SAP connector) and the workflow trigger. This seems to have some limit on the size of the message which is exceeded somehow. 

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create a new logic app
2. Configure it to be able to run netfx code
3. Add SAP DLLs
4. Create new workflow with sap trigger
5. Send a large message (>15MB) via RFC

Expected result: workflow is triggered
Actual result: workflow is not triggered, but if you enable NCO tracing, you'll find the complete message in the logs and the exception "SAP.Middleware.Connector.RfcAbapException: RpcException: Received message exceeds the maximum configured message size."

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Respond_to_SAP_server": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "body": "<@{variables('OperationID')}Response></@{variables('OperationID')}Response>"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "sap",
                        "operationId": "respondToSapServer",
                        "serviceProviderId": "/serviceProviders/sap"
                    }
                },
                "runAfter": {
                    "Scope": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Scope": {
                "type": "Scope",
                "actions": {
                    "Create_claim_check": {
                        "type": "InvokeFunction",
                        "inputs": {
                            "functionName": "ServiceBus.CreateClaimCheck",
                            "parameters": {
                                "target": "@variables('OperationID')",
                                "messageContent": "@string(triggerBody()?['content'])"
                            }
                        }
                    },
                    "Send_message": {
                        "type": "ServiceProvider",
                        "inputs": {
                            "parameters": {
                                "entityName": "pl-quintiq-push",
                                "message": {
                                    "contentData": "@body('Create_claim_check')",
                                    "userProperties": {
                                        "TargetApplication": "SAP",
                                        "TargetEnvironment": "TST",
                                        "TargetPortType": "RequestResponse",
                                        "OperationId": "@{variables('OperationID')}"
                                    }
                                }
                            },
                            "serviceProviderConfiguration": {
                                "connectionName": "serviceBus",
                                "operationId": "sendMessage",
                                "serviceProviderId": "/serviceProviders/serviceBus"
                            }
                        },
                        "runAfter": {
                            "Create_claim_check": [
                                "SUCCEEDED"
                            ]
                        }
                    }
                },
                "runAfter": {
                    "Initialize_variable": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Initialize_variable": {
                "type": "InitializeVariable",
                "inputs": {
                    "variables": [
                        {
                            "name": "OperationID",
                            "type": "string",
                            "value": "@triggerBody()?['rfcServerContext']?['FunctionName']"
                        }
                    ]
                },
                "runAfter": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_message_is_received": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "idocFormat": "FlatFile",
                        "DegreeOfParallelism": 10,
                        "ReceiveIDocsWithUnreleasedSegments": true,
                        "GatewayHost": "@parameters('sap-gateway-host')",
                        "GatewayService": "@parameters('sap-gateway-service')",
                        "ProgramId": "@parameters('sap-program-id')"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "sap",
                        "operationId": "SapTrigger",
                        "serviceProviderId": "/serviceProviders/sap"
                    }
                }
            }
        }
    },
    "kind": "Stateful"
}
```

**Comment by BigSlimeGuy** [comment]
Great, let me know if I can do anything to help.
