### ISSUE TITLE
Issue when using webhook action 

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#180]
I have a durable azure function (Long Running) and calling that from Logic Apps using HttpWebHook action. This design works perfectly in the Logic Apps Cloud version. 

On the local version, there is two issues.

1. Design Issue: As we are running logic apps locally, I will have to call the local azure function. I had set the local azure function in debug mode (Changed the port to 7073). On the Logic app, I am not able to set the url

![image](https://user-images.githubusercontent.com/4720931/94538431-f021b900-023b-11eb-9ba1-277d5c2b7fa6.png)

As you can see from the above picture, the designer complains about Invalid Url. I think the designer should be fixed to allow local urls. As a workaround, I added an entry to the hosts file

![image](https://user-images.githubusercontent.com/4720931/94537978-55c17580-023b-11eb-873e-39c85cfab095.png)

After doing the above, the designer doesn't show up an error. 

2: Runtime Issue: I tried running the logic app now, but I am getting the below error

I think the main issue here is "'System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead". 

[2020-09-29T08:55:11.534]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 
count)
[2020-09-29T08:55:11.537]    at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
[2020-09-29T08:55:11.539]    at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
[2020-09-29T08:55:11.541]    at System.IO.StreamReader.ReadSpan(Span`1 buffer)
[2020-09-29T08:55:11.542]    at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
[2020-09-29T08:55:11.544]    at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
[2020-09-29T08:55:11.545]    at Newtonsoft.Json.JsonTextReader.ParseValue()
[2020-09-29T08:55:11.547]    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
[2020-09-29T08:55:11.548]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
[2020-09-29T08:55:11.550]    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
[2020-09-29T08:55:11.552]    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
[2020-09-29T08:55:11.587]    at System.Net.Http.Formatting.JsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
[2020-09-29T08:55:11.589]    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
[2020-09-29T08:55:11.592]    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStreamAsync(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
[2020-09-29T08:55:11.594] --- End of stack trace from previous location where exception was thrown ---
[2020-09-29T08:55:11.595]    at Microsoft.Azure.Workflows.Data.Engines.FlowHttpEngine.ReadHttpContentWithCancellation(IFlowEventSource flowLogger, IDisposable message, HttpContent content, CancellationToken cancellationToken, Boolean throwOnError)
[2020-09-29T08:55:11.598]    at Microsoft.Azure.Workflows.Data.Engines.FlowHttpEngine.GetHttpActionOutput(IFlowEventSource flowLogger, HttpRequestMessage request, Boolean shouldIncludeAuthorizationHeadersInOutputs, CancellationToken cancellationToken)
[2020-09-29T08:55:11.600]    at Microsoft.Azure.Workflows.Data.Engines.FlowHttpEngine.GetOperationOutput(HttpRequestMessage request, IFlowEventSource flowLogger, Boolean shouldIncludeAuthorizationHeadersInOutputs, CancellationToken cancellationToken)
[2020-09-29T08:55:11.605]    at Microsoft.Azure.Workflows.Web.Common.Extensions.IRequestHolderExtensions.GetFlowOperationResultBasedOnOutputValidation(IRequestHolder requestHolder, FlowContext context, FlowRunActionJobMetadata metadata, CancellationToken cancellationToken)
[2020-09-29T08:55:11.607]    at Microsoft.Azure.Workflows.Web.Common.RequestHandlers.FlowRunApiRequestHandler.RunAction(FlowContext context, String runName, String actionName, CancellationToken cancellationToken)
[2020-09-29T08:55:11.609]    at Microsoft.Azure.Workflows.Web.Controllers.EdgeFlowRunActionController.RunAction(String scaleUnit, String flowName, String runName, String actionName, CancellationToken cancellationToken)
[2020-09-29T08:55:11.611]    at Microsoft.Azure.Workflows.Web.FlowExtensionRouteInitializer.Invoke(HttpRequestMessage request, CancellationToken 
cancellationToken)
[2020-09-29T08:55:11.613]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionHttpRequestHandler.HandleRequest(HttpRequestMessage request, 
CancellationToken cancellationToken)
[2020-09-29T08:55:11.615]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionRequestCancellationHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)
[2020-09-29T08:55:11.617]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionAuthorizationHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)
[2020-09-29T08:55:11.620]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionErrorResponseHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)'.', exception='System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or 
set AllowSynchronousIO to true instead.
[2020-09-29T08:55:11.622]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 
count)
[2020-09-29T08:55:11.624]    at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
[2020-09-29T08:55:11.627]    at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
[2020-09-29T08:55:11.628]    at System.IO.StreamReader.ReadSpan(Span`1 buffer)
[2020-09-29T08:55:11.630]    at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
[2020-09-29T08:55:11.631]    at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
[2020-09-29T08:55:11.633]    at Newtonsoft.Json.JsonTextReader.ParseValue()
[2020-09-29T08:55:11.634]    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
[2020-09-29T08:55:11.636]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
[2020-09-29T08:55:11.638]    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
[2020-09-29T08:55:11.640]    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
[2020-09-29T08:55:11.642]    at System.Net.Http.Formatting.JsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
[2020-09-29T08:55:11.644]    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
[2020-09-29T08:55:11.646]    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStreamAsync(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
[2020-09-29T08:55:11.648] --- End of stack trace from previous location where exception was thrown ---
[2020-09-29T08:55:11.649]    at Microsoft.Azure.Workflows.Data.Engines.FlowHttpEngine.ReadHttpContentWithCancellation(IFlowEventSource flowLogger, IDisposable message, HttpContent content, CancellationToken cancellationToken, Boolean throwOnError)
[2020-09-29T08:55:11.652]    at Microsoft.Azure.Workflows.Data.Engines.FlowHttpEngine.GetHttpActionOutput(IFlowEventSource flowLogger, HttpRequestMessage request, Boolean shouldIncludeAuthorizationHeadersInOutputs, CancellationToken cancellationToken)
[2020-09-29T08:55:11.656]    at Microsoft.Azure.Workflows.Data.Engines.FlowHttpEngine.GetOperationOutput(HttpRequestMessage request, IFlowEventSource flowLogger, Boolean shouldIncludeAuthorizationHeadersInOutputs, CancellationToken cancellationToken)
[2020-09-29T08:55:11.658]    at Microsoft.Azure.Workflows.Web.Common.Extensions.IRequestHolderExtensions.GetFlowOperationResultBasedOnOutputValidation(IRequestHolder requestHolder, FlowContext context, FlowRunActionJobMetadata metadata, CancellationToken cancellationToken)
[2020-09-29T08:55:11.660]    at Microsoft.Azure.Workflows.Web.Common.RequestHandlers.FlowRunApiRequestHandler.RunAction(FlowContext context, String runName, String actionName, CancellationToken cancellationToken)
[2020-09-29T08:55:11.662]    at Microsoft.Azure.Workflows.Web.Controllers.EdgeFlowRunActionController.RunAction(String scaleUnit, String flowName, String runName, String actionName, CancellationToken cancellationToken)
[2020-09-29T08:55:11.665]    at Microsoft.Azure.Workflows.Web.FlowExtensionRouteInitializer.Invoke(HttpRequestMessage request, CancellationToken 
cancellationToken)
[2020-09-29T08:55:11.668]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionHttpRequestHandler.HandleRequest(HttpRequestMessage request, 
CancellationToken cancellationToken)
[2020-09-29T08:55:11.671]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionRequestCancellationHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)
[2020-09-29T08:55:11.673]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionAuthorizationHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)
[2020-09-29T08:55:11.675]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionErrorResponseHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)', organizationId='', activityVector='IN.08', additionalProperties='', extensionVersion='1.0.0.0', siteName='', slotName='', activityId='b2cad54b-dcd6-4ca2-bcaf-fb61c20c78fc'.
[2020-09-29T08:55:11.779] Incoming HTTP request ends with server failure: correlationId='b2cad54b-dcd6-4ca2-bcaf-fb61c20c78fc', authorizationSource='Direct', authorizationAction='', operationName='POST/RUNTIME/WORKFLOW/PROD-00/2CF56FDD4909498E832F69C04BF00D74/08586002372038017079576383336CU00/HTTP_WEBHOOK/', httpMethod='POST', hostName='localhost', targetUri='http://localhost:7071/runtime/webhooks/workflow/scaleUnits/prod-00/workflows/2cf56fdd4909498e832f69c04bf00d74/runs/08586002372038017079576383336CU00/actions/HTTP_Webhook/run?api-version=2019-10-01-edge-preview&code=*sanitized*&sp=%2fruns%2f08586002372038017079576383336CU00%2factions%2fHTTP_Webhook%2frun%2c%2fruns%2f08586002372038017079576383336CU00%2factions%2fHTTP_Webhook%2fread&sv=1.0&sig=*sanitized*', userAgent='', clientRequestId='', clientSessionId='', clientIpAddress='', clientApplicationId='', apiVersion='2019-10-01-edge-preview', contentLength='171', serviceRequestId=':b2cad54b-dcd6-4ca2-bcaf-fb61c20c78fc', durationInMilliseconds='682', 
httpStatusCode='500', exceptionMessage='', errorCode='', failureCause='service', errorMessage='', referer='<null>', commandName='', parameterSetName='', contentType='application/json; charset=utf-8', contentEncoding='', armServiceRequestId='', organizationId='', activityVector='IN', locale='', additionalProperties='', targetResourceProvider='', targetResourceType='', extensionVersion='1.0.0.0', siteName='', slotName='', activityId='b2cad54b-dcd6-4ca2-bcaf-fb61c20c78fc'.
[2020-09-29T08:56:43.617] Incoming HTTP request ends with server failure: correlationId='ee644c41-cb84-40bd-8611-2e89e7cd35e4', authorizationSource='Direct', authorizationAction='', operationName='POST/API/TRIGGERS/INVOKE/TRIGGERS/PATHS/INVOKE', httpMethod='POST', hostName='localhost', targetUri='http://localhost:7071/api/Stateful1/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=*sanitized*', userAgent='PostmanRuntime/7.26.5', clientRequestId='', clientSessionId='', clientIpAddress='', clientApplicationId='', apiVersion='2020-05-01-preview', contentLength='202', serviceRequestId=':ee644c41-cb84-40bd-8611-2e89e7cd35e4', durationInMilliseconds='122025', httpStatusCode='504', exceptionMessage='', errorCode='', failureCause='trigger', errorMessage='', referer='<null>', commandName='', parameterSetName='', contentType='application/json; charset=utf-8', contentEncoding='', armServiceRequestId='', organizationId='', activityVector='IN', locale='', additionalProperties='', targetResourceProvider='', targetResourceType='', extensionVersion='1.0.0.0', siteName='', slotName='', activityId='ee644c41-cb84-40bd-8611-2e89e7cd35e4'.

**Comment by rohithah** [comment]
can you try adding following to the app settings:

FUNCTIONS_V2_COMPATIBILITY_MODE=true

**Comment by shankarmaha** [comment]
@rohithah, Brilliant. It worked flawlessly after the setting update. I tested that out in Azure and it worked correctly. I am not sure if the design issue is really a issue. Do you recommend my suggested approach?

**Comment by rohithah** [comment]
We understand what is causing this and planning to fix in an upcoming release. We can use this as a workaround for now.

**Comment by shankarmaha** [comment]
Thanks @rohithah
