### ISSUE TITLE
Runtime failure appending for-each/current-item to an array variable

### ISSUE THREAD

**Issue by robin-parker** [Azure/logicapps#225]
I'm getting a repeatable failure in a V2 logic app when attempting to append the current-item in a for-each loop to an array variable, the same code is working fine in a V1 logic app.

Chasing the tracking Id into AppInsights it seems as though there is a missing configuration value causing the stack trace.
```
Job error: correlationId='1a592694-ac57-4137-aeb4-2f13375fabca', operationName='FlowRunActionJobCallback.OnJobExecute', jobPartition='6008A10AB79D4919A08B4193C194314B:2D08585930537532288769713651254CU00', jobId='08585930537532288769713651254CU00:2DFOR:3A5FEACH:3A5FITEM:2D00000000:2D00000000:2D00000000', message='The unknown exception is encountered. The current flow run job is failed.', exception='System.Configuration.ConfigurationErrorsException: Unable to load configuration setting 'Microsoft.Azure.Workflows.SkuExtensions.DefaultAppendArrayItemsLimit.ConsumptionSku'.
   at Microsoft.WindowsAzure.ResourceStack.Common.Services.AzureConfigurationManager.GetConfigurationNumberInternal(String settingName)
   at Microsoft.WindowsAzure.ResourceStack.Common.Services.AzureConfigurationManager.GetConfigurationNumber(String settingName)
   at Microsoft.WindowsAzure.ResourceStack.Common.Services.CloudConfigurationManager.GetConfigurationNumber(String settingName)
   at Microsoft.Azure.Workflows.Data.Extensions.SkuExtensions.GetDefaultAppendArrayItemsLimit(FlowSku sku, CachedSubscription subscription)
   at Microsoft.Azure.Workflows.Worker.Jobs.VariableAppendArrayActionJob.Validate(FlowRunVariable variable, VariableActionInput actionInput, CachedSubscription subscription)
   at Microsoft.Azure.Workflows.Worker.Jobs.VariableUpdateActionJob.ExecuteVariableOperation(VariableActionInput actionInput, FlowRunActionExecutionContext actionExecutionContext)
...
   at Microsoft.Azure.Workflows.Worker.Jobs.FlowRunActionJobCallback`2.OnJobExecute()', organizationId='', activityVector='IN.0F.IN.09', additionalProperties='{"ParentActivityId":"00-1b64bb4b0ed1cd4680c500638add7ed1-9cd3f4f500163b42-00"}', extensionVersion='1.0.0.0', siteName='aise-digital-dev-logicapps', slotName='Production', activityId='c77ebf0f-3c34-4e94-9ef1-0b6efdac068f'.
```

**Comment by rarayudu** [comment]
Thanks for reporting this. We found the issue and it will get fixed as part of our next release.

**Comment by rarayudu** [comment]
As a workaround, you can add the setting "Runtime.SkuExtensions.DefaultAppendArrayItemsLimit.ConsumptionSku" and set the value to "100000" in the host.json extension options.

A sample host.json is below.

{
  "version": "2.0",
  "extensions": {
    "workflow": {
	   "settings": {
			"Runtime.SkuExtensions.DefaultAppendArrayItemsLimit.ConsumptionSku": "100000"
	   }
    }
  }
}

**Comment by nidubey1** [comment]
@robin-parker I have tested this scenario and it works fine in Logic App(single tenant) Standard.
