### ISSUE TITLE
Local webhook debugging exception "System.Diagnostics.PerformanceCounter: Category does not exist" (preview)

### ISSUE THREAD

**Issue by erwinkramer** [Azure/logicapps#238]
During local testing trough visual studio code, I'm experiencing the following exception when I send a HTTP Post to my logic app (preview) trigger.

Everything else is the latest 'stable' release.

```
Azure Functions Core Tools
Core Tools Version:       3.0.3233 Commit hash: d1772f733802122a326fa696dd4c086292ec0171 
Function Runtime Version: 3.0.15193.0

[2021-02-04T15:02:30.216Z] Found C:\Users\SNIP\LogicApps.csproj. Using for user secrets file configuration.

Functions:

        test-SNIP-statefull:  http://localhost:7071/api/SNIP/triggers/manual/invoke

        WorkflowDispatcher: workflowRuntimeTrigger

For detailed output, run func with --verbose flag.
[2021-02-04T15:02:38.680Z] Executing 'Functions.test-SNIP-statefull' (Reason='This function was programmatically called via the host APIs.', Id=663b7849-cee4-4b77-9e00-c69cf2722842)
[2021-02-04T15:02:39.919Z] Incoming HTTP request ends with server failure: correlationId='64a437ca-9b16-4a89-9374-4c1768426644', authorizationSource='Direct', authorizationAction='', operationName='POST/API/TRIGGERS/INVOKE/TRIGGERS/PATHS/INVOKE', httpMethod='POST', hostName='localhost', targetUri='http://localhost:7071/api/test-SNIP-statefull/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2ftriggers%2fmanual%2frun&sv=1.0&sig=*sanitized*', userAgent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.56', clientRequestId='', clientSessionId='', clientIpAddress='', clientApplicationId='', apiVersion='2020-05-01-preview', contentLength='-1', serviceRequestId='', durationInMilliseconds='969', httpStatusCode='0', exceptionMessage='System.InvalidOperationException: Category does not exist.
[2021-02-04T15:02:40.429Z]    at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
[2021-02-04T15:02:40.447Z]    at System.Diagnostics.PerformanceCounter.InitializeImpl()
[2021-02-04T15:02:40.453Z]    at System.Diagnostics.PerformanceCounter.Initialize()
[2021-02-04T15:02:40.455Z]    at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
[2021-02-04T15:02:40.458Z]    at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
[2021-02-04T15:02:40.460Z]    at Microsoft.WindowsAzure.ResourceStack.Common.Utilities.ProcessorTime.GetProcessorTimePerformanceCounter()
[2021-02-04T15:02:40.461Z]    at Microsoft.WindowsAzure.ResourceStack.Common.Utilities.ProcessorTime..cctor()', errorCode='', failureCause='', errorMessage='', referer='<null>', commandName='', parameterSetName='', contentType='', contentEncoding='', armServiceRequestId='', organizationId='', activityVector='IN', locale='en-US, en; q=0.9, nl; q=0.8', additionalProperties='', targetResourceProvider='', targetResourceType='', extensionVersion='1.0.0.0', siteName='', slotName='', activityId='64a437ca-9b16-4a89-9374-4c1768426644'.
[2021-02-04T15:02:40.544Z] Executed 'Functions.test-SNIP-statefull' (Failed, Id=663b7849-cee4-4b77-9e00-c69cf2722842, Duration=1898ms)
[2021-02-04T15:02:40.547Z] System.Private.CoreLib: Exception while executing function: Functions.test-SNIP-statefull. Microsoft.WindowsAzure.ResourceStack: The type initializer for 'Microsoft.WindowsAzure.ResourceStack.Common.Utilities.ProcessorTime' threw an exception. System.Diagnostics.PerformanceCounter: Category does not exist.
[2021-02-04T15:02:42.958Z] Host lock lease acquired by instance ID '000000000000000000000000A606381E'.
```

My function looks like this:
```
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "http",
                "inputs": {
                    "statusCode": 200
                },
                "runAfter": {}
            }
        },
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "schema": {
                        "set": "aaa"
                    }
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}

```

I'm using .NET Core SDK 3.1.405 (x64) but I also tried  3.1.402:

```

{
    "sdk": {
       "version": "3.1.405",
       "rollForward": "disable"
    }
}
```

I modified some versions of Microsoft.NET.Sdk.Functions and Microsoft.Azure.Workflows.WebJobs.Extension to see of that helped, but nothing:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <MSBuildWarningsAsMessages>MSB3246;$(MSBuildWarningsAsMessages)</MSBuildWarningsAsMessages>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7"/>
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Stateful1\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Workflows.WebJobs.Extension" Version="1.0.0.9-preview"/>
  </ItemGroup>
  <ItemGroup>
    <None Update="Artifacts\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Stateful1\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by erwinkramer** [comment]
Somehow a reboot solved this.
