### ISSUE TITLE
Logic App (Standard): support multiple triggers

### ISSUE THREAD

**Issue by gastonmuijtjens** [Azure/logicapps#299]
I have created a _single-tenant_ Logic App (Standard) workflow and want to support multiple triggers in a single workflow. When trying to add multiple triggers, the error below is thrown. The old _Logic App (Consumption)_ resource type seems to support multiple triggers, although not supported by the designer. Please support multiple triggers within a single workflow for the new _Logic App (Standard)_ resource type.

```json
{
     // [...]
    "triggers": {
            "Recurrence": {
                "type": "Recurrence",
                "recurrence": {
                    "frequency": "Day",
                    "interval": 1,
                    "schedule": {
                        "hours": [
                            "17"
                        ],
                        "minutes": [
                            0
                        ]
                    }
                }
            },
            "manual": {
                "inputs": {},
                "kind": "Http",
                "type": "Request"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
}
```

```
[2021-05-31T09:52:00.974Z] Workflow Error: operationName='WorkflowDefinitionProvider.ProcessWorkflow', message='Workflow '<workflow_name>' validate and create workflow operation failed, the exception is 'The workflow '<workflow_name>' is not valid as the number of triggers found in workflow is '2' expected '1'.'', exception='Microsoft.Azure.Workflows.Common.ErrorResponses.ErrorResponseMessageException: The workflow '<workflow_name>' is not valid as the number of triggers found in workflow is '2' expected '1'.
[2021-05-31T09:52:00.974Z]    at Microsoft.Azure.Workflows.Data.Common.EdgeValidation.FlowSingleTrigger(FlowPropertiesDefinition definition, String flowName)
[2021-05-31T09:52:00.974Z]    at Microsoft.Azure.Workflows.Data.Common.EdgeValidation.FlowRunEdgeTriggerType(FlowPropertiesDefinition definition, String flowName)
[2021-05-31T09:52:00.974Z]    at Microsoft.Azure.Workflows.Data.Engines.EdgeFlowDefinitionValidationEngine.OnValidateFlowTrigger(FlowPropertiesDefinition definition, String flowName, String triggerName, InsensitiveDictionary`1 parameterValues, FlowOperationConfiguration flowOperationConfiguration, Boolean hasOpenApiOperationInWorkflow, Boolean shouldValidateConnectionReferences)
[2021-05-31T09:52:00.974Z]    at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlowTrigger(FlowPropertiesDefinition definition, String flowName, String triggerName, FlowOperationConfiguration flowOperationConfiguration, InsensitiveDictionary`1 parameterValues, Boolean hasOpenApiOperationInWorkflow, Boolean shouldValidateConnectionReferences)
[2021-05-31T09:52:00.974Z]    at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlowTriggers(FlowPropertiesDefinition definition, InsensitiveDictionary`1 parameterValues, Boolean shouldValidateConnectionReferences, String flowName)
[2021-05-31T09:52:00.974Z]    at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlowTemplate(FlowPropertiesDefinition definition, InsensitiveDictionary`1 templateParameters, String flowName, IntegrationAccount integrationAccount, Boolean shouldValidateConnectionReferences)
[2021-05-31T09:52:00.974Z]    at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlow(String flowName, Flow existingFlow, FlowPropertiesDefinition definition, IntegrationAccount integrationAccount, Boolean shouldValidateConnectionReferences)
[2021-05-31T09:52:00.974Z]    at Microsoft.Azure.Workflows.Web.Engines.EdgeFlowWebManagementEngine.ValidateAndCreateFlow(String flowName, FlowPropertiesDefinition definition)
[2021-05-31T09:52:00.974Z]    at Microsoft.WindowsAzure.ResourceStack.Common.Algorithms.AsyncRetry.Retry(Func`1 action, Int32 retryCount, TimeSpan retryInterval, CancellationToken cancellationToken, Nullable`1 retryTimeout, Func`2 isRetryable, Action`1 errorAction, Func`2 retryAfter)
[2021-05-31T09:52:00.974Z]    at Microsoft.WindowsAzure.ResourceStack.Common.Algorithms.AsyncRetry.Retry(Func`1 action, Int32 retryCount, TimeSpan retryInterval, CancellationToken cancellationToken, Nullable`1 retryTimeout, Func`2 isRetryable, Action`1 errorAction, Func`2 retryAfter)
[2021-05-31T09:52:00.974Z]    at Microsoft.Azure.Workflows.WebJobs.Extensions.Initialization.WorkflowFunctionDefinitionProvider.ProcessWorkflow(FlowFunction flowFunction, ConcurrentDictionary`2 flowsProcessed)', extensionVersion='1.0.0.0', siteName='UNDEFINED_SITE_NAME', slotName='', activityId='613296db-f9aa-4b0c-a95a-a78d51416cf3'.
```

**Comment by devin-simoneaux** [comment]
@gastonmuijtjens we do not have any plans to support multiple triggers for Logic Apps (Standard). At this time, the suggested approach is to use a parent-child Logic App pattern to achieve the same goal.

**Comment by KiranmaiS** [comment]
Hello @gastonmuijtjens, I hope we answered your query. Please let us know if you have any other thoughts or questions. 
We shall proceed with the closure of this request for now.

**Comment by sarojkumar-shell** [comment]
Hello @devin-simoneaux, is there any plan now to introduce multiple triggers in Logic App standard workflow?
