### ISSUE TITLE
using result function on a scope causes interenal server error when running locally but not azure.

### ISSUE THREAD

**Issue by skyaddict** [Azure/logicapps#369]
I am debugging a logic app. The following call fails with 

                    "Get_Scope_Failure": {
                        "type": "Query",
                        "inputs": {
                            "from": "@result('Scope')",
                            "where": "@equals(item()['status'], 'Failed')"
                        },

![image](https://user-images.githubusercontent.com/18058674/131915742-c4b072b6-844f-4147-8c2f-f3b3ec1889f6.png)

If I remove the call to the result function the error goes away. This works as expected when running in azure

add the following workflow to a VSCode logic app project. Run the logic app from VSCode.

`{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Initialize_variable": {
                "type": "InitializeVariable",
                "inputs": {
                    "variables": [
                        {
                            "name": "test",
                            "type": "string"
                        }
                    ]
                },
                "runAfter": {}
            },
            "Scope": {
                "type": "Scope",
                "actions": {
                    "Set_variable": {
                        "type": "SetVariable",
                        "inputs": {
                            "name": "test",
                            "value": "teststring"
                        },
                        "runAfter": {}
                    }
                },
                "runAfter": {
                    "Initialize_variable": [
                        "Succeeded"
                    ]
                }
            },
            "Compose": {
                "type": "Compose",
                **"inputs": "@result('Scope')",**
                "runAfter": {
                    "Scope": [
                        "Succeeded"
                    ]
                }
            }
        },
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}`

result: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Microsoft.Azure.Workflows.Data.Entities.FlowOperationResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. Full exception stack included below.

expected result: the results array from the scope will be output by the compose step.

Exception:

[2021-09-03T17:11:41.358Z] Executed 'Functions.WorkflowDispatcher' (Failed, Id=910860a8-a823-4fcc-b825-f061f0add2c8, Duration=176ms)
[2021-09-03T17:11:41.360Z] System.Private.CoreLib: Exception while executing function: Functions.WorkflowDispatcher. Newtonsoft.Json: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Microsoft.Azure.Workflows.Data.Entities.FlowOperationResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
[2021-09-03T17:11:41.361Z] To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
[2021-09-03T17:11:41.362Z] Path ''.
[2021-09-03T17:11:41.368Z] Job error: correlationId='8435a9bd-1d55-4162-9036-1773da1aaaad', operationName='FlowRunActionJobCallback.OnJobExecute', jobPartition='667304A1B8894703864D6D192C61CD08:2D08585709177849964319256369672CU00', jobId='08585709177849964319256369672CU00', message='The unknown exception is encountered. The current flow run job is failed.', exception='Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Microsoft.Azure.Workflows.Data.Entities.FlowOperationResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
[2021-09-03T17:11:41.369Z] To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
[2021-09-03T17:11:41.370Z] Path ''.
[2021-09-03T17:11:41.371Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
[2021-09-03T17:11:41.372Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
[2021-09-03T17:11:41.372Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[2021-09-03T17:11:41.373Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
[2021-09-03T17:11:41.374Z]    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
[2021-09-03T17:11:41.374Z]    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
[2021-09-03T17:11:41.375Z]    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
[2021-09-03T17:11:41.375Z]    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
[2021-09-03T17:11:41.376Z]    at Microsoft.WindowsAzure.ResourceStack.Common.Json.JsonExtensions.FromJToken[T](JToken jtoken)
[2021-09-03T17:11:41.376Z]    at Microsoft.Azure.Workflows.Worker.Jobs.FlowRunActionJobCallback`2.<>c.<GetDebugContext>b__153_19(KeyValuePair`2 kvp)
[2021-09-03T17:11:41.377Z]    at Microsoft.WindowsAzure.ResourceStack.Common.Extensions.IEnumerableExtensions.ToInsensitiveDictionary[TSource,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
[2021-09-03T17:11:41.378Z]    at Microsoft.Azure.Workflows.Worker.Jobs.FlowRunActionJobCallback`2.GetDebugContext(FlowRun run, InsensitiveDictionary`1 dependenciesJobMetadata, FlowRunOperationDependencyTrackingContext dependencyTrackingContext)
[2021-09-03T17:11:41.378Z]    at Microsoft.Azure.Workflows.Data.Entities.FlowRunActionExecutionContext.GetDebugContext()
[2021-09-03T17:11:41.379Z]    at Microsoft.Azure.Workflows.Worker.Jobs.FlowRunActionJobCallback`2.EnterOnActionStartBreakpointIfExists(FlowRunActionExecutionContext actionExecutionContext, JToken inputs)
[2021-09-03T17:11:41.379Z]    at Microsoft.Azure.Workflows.Worker.Jobs.FlowRunActionJobCallback`2.GetActionInput(FlowRunActionExecutionContext actionExecutionContext)
[2021-09-03T17:11:41.380Z]    at Microsoft.Azure.Workflows.Worker.Jobs.ComposeActionJob.OnExecuteAction(FlowRunActionExecutionContext actionExecutionContext, FlowOperationState operationState)
[2021-09-03T17:11:41.381Z]    at Microsoft.Azure.Workflows.Worker.Jobs.FlowRunActionWithUntilConditionsJobCallback`1.ExecuteAction(FlowRunActionExecutionContext actionExecutionContext)
[2021-09-03T17:11:41.381Z]    at Microsoft.Azure.Workflows.WebJobs.Engines.FunctionActionExecutionEngine.ExecuteEdgeActionCallback(EdgeActionExecutionContext edgeExecutionContext)
[2021-09-03T17:11:41.382Z]    at Microsoft.Azure.Workflows.WebJobs.Extensions.Trigger.WorkflowRuntimeTriggerProcessor.HandleFlowTrigger(EdgeActionExecutionContext edgeBindingExecutionContext, Binder binder)
[2021-09-03T17:11:41.382Z]    at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
[2021-09-03T17:11:41.383Z]    at Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.MethodInvoker`2.InvokeAsync(Object target, Object[] parameters) in D:\a\1\s\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs:line 533
[2021-09-03T17:11:41.383Z]    at Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in D:\a\1\s\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs:line 272      
[2021-09-03T17:11:41.384Z]    at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in D:\a\1\s\src\WebJobs.Script\Description\FunctionInvokerBase.cs:line 82
[2021-09-03T17:11:41.385Z]    at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
[2021-09-03T17:11:41.385Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52       
[2021-09-03T17:11:41.386Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 555
[2021-09-03T17:11:41.387Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 501
[2021-09-03T17:11:41.387Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279
[2021-09-03T17:11:41.388Z]    at Microsoft.Azure.Workflows.WebJobs.Engines.FunctionActionExecutionEngine.ExecuteAction(Func`2 flowRunActionCallback, FlowRunActionExecutionContext flowRunActionExecutionContext, CancellationToken cancellationToken)        
[2021-09-03T17:11:41.388Z]    at Microsoft.Azure.Workflows.Worker.Jobs.FlowRunActionJobCallback`2.ExecuteActionAndHandleExecutionResultException(FlowRunActionExecutionContext actionExecutionContext)
[2021-09-03T17:11:41.389Z]    at Microsoft.Azure.Workflows.Worker.Jobs.FlowRunActionJobCallback`2.OnExecuteAction(FlowRunActionExecutionContext actionExecutionContext)
[2021-09-03T17:11:41.390Z]    at Microsoft.Azure.Workflows.Worker.Jobs.FlowRunActionJobCallback`2.OnJobExecuteAction(FlowRunActionExecutionContext actionExecutionContext)
[2021-09-03T17:11:41.390Z]    at Microsoft.Azure.Workflows.Worker.Jobs.FlowRunActionJobCallback`2.OnJobExecute()', organizationId='', activityVector='IN.03', additionalProperties='', extensionVersion='1.0.0.0', siteName='UNDEFINED_SITE_NAME', slotName='', activityId='e7605a8b-b100-4dfa-bd1b-4df6832fc216'.

**Comment by hongzli** [comment]
Thanks for reporting this. This is a bug and we will work on a fix.

**Comment by John-Bosch** [comment]
Is there any update on this bug? It's been hanging around for 5 months now and effectively means we can't have any form of exception handling and also debug locally.

**Comment by hongzli** [comment]
The fix has been made and is currently being deployed. ETA is roughly 2 weeks. Sorry for the long wait.
