### ISSUE TITLE
Error:  The system cannot find the file specified.

### ISSUE THREAD

**Issue by Baran121** [Azure/logicapps#445]
﻿ RequestResponse
   Source: TestCases.cs line 24
   Duration: 24.8 sec

  Message: 
Test method TestCases.TestCases.RequestResponse threw exception: 
System.ComponentModel.Win32Exception: The system cannot find the file specified.

  Stack Trace: 
Process.StartWithCreateProcess(ProcessStartInfo startInfo)
Process.Start()
WorkflowTestHost.StartFunctionRuntime(WorkflowTestInput[] inputs, String localSettings, String parameters, String connectionDetails, String host, DirectoryInfo artifactsDirectory) line 160
WorkflowTestHost.ctor(WorkflowTestInput[] inputs, String localSettings, String parameters, String connectionDetails, String host, DirectoryInfo artifactsDirectory) line 47
TestCases.RequestResponse() line 30

  Standard Output: 
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at TestFramework.WorkflowTestHost.StartFunctionRuntime(WorkflowTestInput[] inputs, String localSettings, String parameters, String connectionDetails, String host, DirectoryInfo artifactsDirectory) in C:\Users\baranee\Documents\1\LogicAppsSampleTestFramework\TestFramework\WorkflowTestHost.cs:line 160

**Comment by Baran121** [comment]
install https://functionscdn.azureedge.net/public/artifacts/v4/latest/func-cli-x86.msi and this problem will be gone
