### ISSUE TITLE
In VSCode, Workflow Fails To Start after designer changes - Azurite 3.17.1 Extension

### ISSUE THREAD

**Issue by dancurtiss** [Azure/logicapps#528]
Scenario:
1) Logic App workflow starts and runs correctly
2) Make any updates to logic app workflow which would require a rebuild of the logic app
3) Attempt to run logic app again 

```
2022-04-29T14:28:28.932Z] Workflow Error: operationName='WorkflowDefinitionProvider.ProcessWorkflow', message='Workflow 'xxx' validate and create workflow 
failed, the error is 'Unexpected HTTP status code '412'.'', exception='Microsoft.WindowsAzure.Storage.StorageException: Unexpected HTTP status code '412'.
[2022-04-29T14:28:28.936Z]    at Microsoft.WindowsAzure.ResourceStack.Common.Storage.Http.Parsers.FastCloudTableParser.UpdateEntitiesFromResponse(TableBatchOperation batch, MemoryStream content, RequestResult operationResult)

```

**Comment by dancurtiss** [comment]
Thank you for the input.  It does seem to be due to VSCode extension updates to Azure Logic App Designer and maybe more importantly Azurite.  

I've downgraded these to: 

Azure Logic Apps (standard) v1.0.14
Azurite v3.16

Seems to be working again now.  I'll leave this open to get notified when fixed.

**Comment by siddheshdp** [comment]
Hello,
I am also getting similar exception, I degrade the version but looks like same issue except getting error code 404
I  did the same thing - Azure Logic Apps (standard) v1.0.14
Azurite v3.16

Workflow Error: operationName='WorkflowDefinitionProvider.ProcessWorkflow', message='Workflow 'test' validate and create workflow failed, the error is 'One or more errors occurred. (Unexpected HTTP status code 'NotFound'.) (Unexpected HTTP status code 'NotFound'.)'', exception='System.AggregateException: One or more errors occurred. (Unexpected HTTP status code 'NotFound'.) (Unexpected HTTP status code 'NotFound'.)
Microsoft.WindowsAzure.Storage.StorageException: Unexpected HTTP status code 'NotFound'.
 System.Net.WebException: The remote server returned an error: (404) Not Found.

**Comment by HLChucky** [comment]
> Thank you for the input. It does seem to be due to VSCode extension updates to Azure Logic App Designer and maybe more importantly Azurite.
> 
> I've downgraded these to:
> 
> Azure Logic Apps (standard) v1.0.14 Azurite v3.16
> 
> Seems to be working again now. I'll leave this open to get notified when fixed.

For me the issue was the new Azurite extension version - downgrading to v3.16 resolved the issue. I've kept the Azure Logic Apps Standard extension at v1.0.19 and don't have any issues. 

One thing to add is that I had to delete the existing Azurite files (__blobstorage__, __azurite_db_blob__.json etc.) that had been created and reload VSCode to get rid of the error.

**Comment by gastonmuijtjens** [comment]
I also have issues with Logic Apps (Standard) after upgrading Azurite to version 3.17.x. However, I don't get any error messages but when I execute a workflow it keeps running on the first step.

I downgraded Azurite and it started working again, VSCode extension version is 1.0.19

**Comment by dancurtiss** [comment]
I've confirmed the issue is only with the Azurite Extension and not the Azure Logic Apps (standard) extension as well.

**Comment by michaelstephensonuk** [comment]
Hi Guys
If you get stuck on this another workaround is to change the connection string to use a storage account in azure rather than Azurite.  Not ideal but hopefully helps people unblock until the product team(s) can address the issue

**Comment by skastberg** [comment]
The issue seems to happen when I'm in **debug mode** and **add a new action**. If I remove the action it starts working again. Adding actions while not debugging works fine. That said 3.17.1 of Azurite seems to leave the executions as running even if those are done.
![image](https://user-images.githubusercontent.com/17530167/168467724-4b10a45c-5577-4799-b3b4-bfdef91f33c0.png)

If I open one of those running events you can see that all actions are executed.
![image](https://user-images.githubusercontent.com/17530167/168467762-5489db0c-b3c6-42e3-8824-e59a1b09a73f.png)

**Comment by Garyljackson** [comment]
Hi Everyone

I ran into this today as well - another workaround I have found is to use the full local development connection from the Azurite documentation in your `local.settings.json` file for the `AzureWebJobsStorage` setting - instead of `UseDevelopmentStorage=true`


I tested this using Azurite v3.18.0

Your `local.settings.json` should look this like
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;",
    "WORKFLOWS_SUBSCRIPTION_ID": "",
    "FUNCTIONS_WORKER_RUNTIME": "node"
  }
}
```

Documented here:
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=docker-hub#http-connection-strings

**Comment by nareshnagpal06** [comment]
I had same issue. The very first time, running F5 from VScode works and workflow URL is shown successful in terminal. 

<img width="339" alt="image" src="https://user-images.githubusercontent.com/33876096/181922244-fda1883b-c555-429c-96d5-7fda1a08e09a.png">


However when I hit the call back url (which is available in workflow overview) from browser/postman, the workflow is triggered fine but its in running state for long time. When I inspected the run, I saw request trigger was completed fine but it got stuck at the Response action. So I deleted the response action (while It was still in debugging mode) just to see if that was the culprit.  And that is when it started giving below issue. 

**Workflow Error: operationName='WorkflowDefinitionProvider.ProcessWorkflow', message='Workflow 'Stateful2' validate and create workflow failed, the error is 'Unexpected HTTP status code '412'.'', exception='Microsoft.WindowsAzure.Storage.StorageException: Unexpected HTTP status code '412'.**

I tried downgrading Azurite version from V1.8 to V1.6 but no luck. 

So as a workaround I had to create a brand new workflow and Not use the response action, then atleast it generates the URL fine and I can get 202 response back. However the run history still shows it as running. 

<img width="383" alt="image" src="https://user-images.githubusercontent.com/33876096/181923685-1977cb0c-1503-473d-a3b2-809bce8e002f.png">

<img width="639" alt="image" src="https://user-images.githubusercontent.com/33876096/181923781-6edf23a2-95d2-4dd7-8d86-0d7487852329.png">

<img width="755" alt="image" src="https://user-images.githubusercontent.com/33876096/181923790-370d5fcb-7b45-43a2-ab25-d9c7cc8710bf.png">


Not sure if its Azurite problem or something to do that fact that I changed the logic app while it was running, following issues still persist 

1. Not able to use Response action
2. Run history shows Running while I have got 202 response back from Postman.

**Comment by kritollm** [comment]
I had same issue. Thanks to the help I found here, it finally works.

Now working with:
Azure Logic Apps (standard) v1.0.19  (VSCode extension)
Azurite v3.16 (VSCode extension)

**Comment by manoelvlm** [comment]
Hi @nareshnagpal06 

The same behavior is happening to me. Did you find any solution?

**Comment by yoHasse** [comment]
Not working for me, also tried all the workarounds in this issue.

**Comment by yoHasse** [comment]
Ok got it to work... sort of.

* Uninstalled Azurite (Extension) and Downloaded/installed from GitHub source.
* Set the folder to C:\Users\<MyUserName>\.azurite\
* Ran debug and it worked.
* Edited the designer and ran again which failed with the same error.
* Removed all the files in the .azurite folder.
* Ran again and it works.

It fails as soon as I edit in the designer so I have to remove all files between runs.

The Azurite logger gives the below errors "ResourceNotFound" and "Precondition Failed".
```
2022-09-07T10:44:09.500Z afbae5cb-72db-4356-bd56-312d915f1622 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-09-07T10:44:09.500Z afbae5cb-72db-4356-bd56-312d915f1622 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage="The specified resource does not exist."  ErrorHTTPStatusCode=404 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"ResourceNotFound","x-ms-request-id":"afbae5cb-72db-4356-bd56-312d915f1622","x-ms-version":"2021-10-04"} ErrorHTTPBody="{\"odata.error\":{\"code\":\"ResourceNotFound\",\"message\":{\"lang\":\"en-US\",\"value\":\"The specified resource does not exist.\\nRequestId:afbae5cb-72db-4356-bd56-312d915f1622\\nTime:2022-09-07T10:44:09.500Z\"}}}" ErrorStack="\"StorageError: The specified resource does not exist.\\n    at Function.getEntityNotFound (C:\\\\Users\\\\marnat\\\\git\\\\_external\\\\Azurite\\\\dist\\\\src\\\\table\\\\errors\\\\StorageErrorFactory.js:76:16)\\n    at TableHandler.queryEntitiesWithPartitionAndRowKey (C:\\\\Users\\\\marnat\\\\git\\\\_external\\\\Azurite\\\\dist\\\\src\\\\table\\\\handlers\\\\TableHandler.js:375:49)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\""
2022-09-07T10:44:09.500Z afbae5cb-72db-4356-bd56-312d915f1622 error: ErrorMiddleware: Set HTTP code: 404
2022-09-07T10:44:09.500Z afbae5cb-72db-4356-bd56-312d915f1622 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=ResourceNotFound
2022-09-07T10:44:09.500Z afbae5cb-72db-4356-bd56-312d915f1622 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=afbae5cb-72db-4356-bd56-312d915f1622
2022-09-07T10:44:09.500Z afbae5cb-72db-4356-bd56-312d915f1622 error: ErrorMiddleware: Set HTTP Header: x-ms-version=2021-10-04
2022-09-07T10:44:09.500Z afbae5cb-72db-4356-bd56-312d915f1622 error: ErrorMiddleware: Set content type: application/json;odata=nometadata;streaming=true;charset=utf-8
2022-09-07T10:44:09.500Z afbae5cb-72db-4356-bd56-312d915f1622 error: ErrorMiddleware: Set HTTP body: "{\"odata.error\":{\"code\":\"ResourceNotFound\",\"message\":{\"lang\":\"en-US\",\"value\":\"The specified resource does not exist.\\nRequestId:afbae5cb-72db-4356-bd56-312d915f1622\\nTime:2022-09-07T10:44:09.500Z\"}}}"

2022-09-07T10:44:13.861Z 	 warn: TableHandler:mergeEntity() Incoming PartitionKey:C0000 RowKey:E17EAF29EF594EDC82AF62C922989D8B_FlowConsistencyJob-08585390595179472850-Immediate in URL parameters don't align with entity body PartitionKey:undefined RowKey:undefined.
2022-09-07T10:44:13.861Z 492ece8f-92aa-483a-b70c-53459b1f8fcc error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2022-09-07T10:44:13.861Z 492ece8f-92aa-483a-b70c-53459b1f8fcc error: ErrorMiddleware: ErrorName=StorageError ErrorMessage="The update condition specified in the request was not satisfied."  ErrorHTTPStatusCode=412 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"UpdateConditionNotSatisfied","x-ms-request-id":"492ece8f-92aa-483a-b70c-53459b1f8fcc","x-ms-version":"2021-10-04"} ErrorHTTPBody="{\"odata.error\":{\"code\":\"UpdateConditionNotSatisfied\",\"message\":{\"lang\":\"en-US\",\"value\":\"The update condition specified in the request was not satisfied.\\nRequestId:492ece8f-92aa-483a-b70c-53459b1f8fcc\\nTime:2022-09-07T10:44:13.861Z\"}}}" ErrorStack="\"StorageError: The update condition specified in the request was not satisfied.\\n    at Function.getPreconditionFailed (C:\\\\Users\\\\MyUserName\\\\git\\\\Azurite\\\\dist\\\\src\\\\table\\\\errors\\\\StorageErrorFactory.js:67:16)\\n    at LokiTableMetadataStore.mergeTableEntity (C:\\\\Users\\\\MyUserName\\\\git\\\\Azurite\\\\dist\\\\src\\\\table\\\\persistence\\\\LokiTableMetadataStore.js:498:49)\\n    at LokiTableMetadataStore.insertOrMergeTableEntity (C:\\\\Users\\\\MyUserName\\\\git\\\\Azurite\\\\dist\\\\src\\\\table\\\\persistence\\\\LokiTableMetadataStore.js:299:25)\\n    at TableHandler.mergeEntity (C:\\\\Users\\\\MyUserName\\\\git\\\\Azurite\\\\dist\\\\src\\\\table\\\\handlers\\\\TableHandler.js:284:34)\\n    at TableHandler.mergeEntityWithMerge (C:\\\\Users\\\\MyUserName\\\\git\\\\Azurite\\\\dist\\\\src\\\\table\\\\handlers\\\\TableHandler.js:413:21)\\n    at C:\\\\Users\\\\MyUserName\\\\git\\\\Azurite\\\\dist\\\\src\\\\table\\\\generated\\\\middleware\\\\HandlerMiddlewareFactory.js:58:18\\n    at C:\\\\Users\\\\MyUserName\\\\git\\\\Azurite\\\\dist\\\\src\\\\table\\\\generated\\\\ExpressMiddlewareFactory.js:77:63\\n    at Layer.handle [as handle_request] (C:\\\\Users\\\\MyUserName\\\\git\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at trim_prefix (C:\\\\Users\\\\MyUserName\\\\git\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:328:13)\\n    at C:\\\\Users\\\\MyUserName\\\\git\\\\Azurite\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:286:9\""
2022-09-07T10:44:13.861Z 492ece8f-92aa-483a-b70c-53459b1f8fcc error: ErrorMiddleware: Set HTTP code: 412
2022-09-07T10:44:13.861Z 492ece8f-92aa-483a-b70c-53459b1f8fcc error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=UpdateConditionNotSatisfied
2022-09-07T10:44:13.861Z 492ece8f-92aa-483a-b70c-53459b1f8fcc error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=492ece8f-92aa-483a-b70c-53459b1f8fcc
2022-09-07T10:44:13.861Z 492ece8f-92aa-483a-b70c-53459b1f8fcc error: ErrorMiddleware: Set HTTP Header: x-ms-version=2021-10-04
2022-09-07T10:44:13.861Z 492ece8f-92aa-483a-b70c-53459b1f8fcc error: ErrorMiddleware: Set content type: application/json;odata=nometadata;streaming=true;charset=utf-8
2022-09-07T10:44:13.861Z 492ece8f-92aa-483a-b70c-53459b1f8fcc error: ErrorMiddleware: Set HTTP body: "{\"odata.error\":{\"code\":\"UpdateConditionNotSatisfied\",\"message\":{\"lang\":\"en-US\",\"value\":\"The update condition specified in the request was not satisfied.\\nRequestId:492ece8f-92aa-483a-b70c-53459b1f8fcc\\nTime:2022-09-07T10:44:13.861Z\"}}}"
2022-09-07T10:44:13.861Z 492ece8f-92aa-483a-b70c-53459b1f8fcc info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=412 StatusMessage=Precondition Failed Headers={"server":"Azurite-Table/3.19.0","x-ms-error-code":"UpdateConditionNotSatisfied","x-ms-request-id":"492ece8f-92aa-483a-b70c-53459b1f8fcc","x-ms-version":"2021-10-04","content-type":"application/json;odata=nometadata;streaming=true;charset=utf-8"}

```

**Comment by dancurtiss** [comment]
We are seeing the same issue now as well.  Our workflows that involved blob triggers are now failing.  We are trying rolling back the latest logic app extension update which is from the past week.

**Comment by dancurtiss** [comment]
Even with rollback of Azure Logic Apps (Standard) extension to 1.0.25 we are still seeing the error:

[2022-09-07T16:17:09.410Z] Azure.Storage.Blobs: Service request failed.
[2022-09-07T16:17:09.411Z] Status: 400 (The value for one of the HTTP headers is not in the correct format.)
[2022-09-07T16:17:09.413Z] ErrorCode: InvalidHeaderValue
[2022-09-07T16:17:09.415Z] 
[2022-09-07T16:17:09.416Z] Headers:
[2022-09-07T16:17:09.418Z] Server: Azurite-Blob/3.16.0
[2022-09-07T16:17:09.420Z] x-ms-error-code: InvalidHeaderValue
[2022-09-07T16:17:09.421Z] x-ms-request-id: f6a4d412-fee4-4804-a995-043d1b5e5b87
[2022-09-07T16:17:09.423Z] Date: Wed, 07 Sep 2022 16:17:09 GMT
[2022-09-07T16:17:09.425Z] Connection: keep-alive
[2022-09-07T16:17:09.427Z] Keep-Alive: REDACTED

We were not seeing this on Friday 9/2/22

**Comment by dancurtiss** [comment]
We may resort to using actual azure storage until we can figure out how to get azurite to play nice with logic apps in VS code.  I think this applies specifically to blob triggers as our other triggers continued to work locally I believe.

**Comment by robertcmolidor** [comment]
> We may resort to using actual azure storage until we can figure out how to get azurite to play nice with logic apps in VS code. I think this applies specifically to blob triggers as our other triggers continued to work locally I believe.

This is what we did for now.  leveraging a storage account in azure instead of using Azurite unblocked us.  Hopefully we get to see Azurite working soon!

**Comment by IMeeus** [comment]
Hi, the issues with Azurite 3.17 and later were fixed today in [PR 1661](https://github.com/Azure/Azurite/pull/1661/files).
If you try to run the latest version of [Azurite's master branch](https://github.com/Azure/Azurite), local development with logic apps should work.
