### ISSUE TITLE
Logic Workflow Managed Queue Cannot Be Found By EMA PING On HTTPS.

### ISSUE THREAD

**Issue by klawrawkz** [Azure/logicapps#601]
Hi, my name is klawrawkz. I am fine, how are you?

Here's the scenario. Deploy a logic app (standard) with an azure queues trigger-based workflow via Azure DevOps automation. The service principal owning the logic app host server has an access policy on the queue authorizing it to use the queue. This is a Managed API connection (providers/Microsoft.Web/connections). 

-- Connections Are Managed --
```
       "super-pooper-queue-conn": {
        "connectionRuntimeUrl": "https://8edef5c8e525a860.11.common.logic-eastus2.azure-apihub.net/apim/azurequeues/4db3f428wholebunchastuff7e5f66a2",
        "authentication": { "type": "ManagedServiceIdentity" },
        "connection": {
          "id": "/subscriptions/ab603228-super-subscription-c844cc805171/resourcegroups/super-resource-group/providers/microsoft.web/connections/azurequeues-super-duper-id"
        },
        "api": {
          "id": "/subscriptions/ab603228-super-subscription-c844cc805171/providers/Microsoft.Web/locations/eastus2/managedApis/azurequeues"
        }
      },
```

The queue exists on an azure storage service. It is accessible and so on and so forth. We use automation to deploy the workflow and when we take a look, Viola!! BROKEN. EMA issues a call for history over an https channel.  "**_Failed to get workflow triggers: error null or undefined._**"  By default, the queue does not *seem* to have such a channel since it's a standard storage queue. Do we need to include **in the workflow** an HTTPS trigger containing the connection RunTimeUrl?? What is EMA doing? Why are our queue connections (all of them always) broken by default???

This is routinely hampering our ability to use any automated deployment with logic apps. As the workflow is deployed via a .zip or a nuget package, it is READ ONLY. We cannot edit it. Hence workflow is broken by default, because EMA cannot find the _non-existent_ https endpoint for an azure storage queue, and therefore the "_workflow does not exist_". This is absurd.  

Why absurd you ask?? Let's discuss. We take the **_selfsame json code base_** for 1) the workflow, 2) the connection and deploy this to 3) the selfsame hosting environment after changing the host site's appsetting **_WEBSITE_RUN_FROM_PACKAGE_** to "read/write" aka 0 (zero) and naturally the workflow is still broken when we take a look. **_We then open the workflow in the code "designer" from the portal and make an inconsequential change, say change some display text. Save the "modified" workflow and BLAMMO!!! Now it works...._** DUH.

Yup, all yah needta do is violate some basic DevOps principles, and the whole mess suddenly works. WOW, this is great. Or NOT GREAT depending on your perspective. I'm in the NOT GREAT camp because this is a pain in the butt and runs counter to most devops principles that we adhere to as per policy.
 
What's the story here?  We've gotta get this logic app stuff deployed via automation. Please advise.

Hope you are doing well.

klaw

-- ERROR MESSAGE FOLLOWS --

<pre>
[Microsoft_Azure_EMA]  4:31:21 AM Microsoft_Azure_EMA Microsoft_Azure_EMA: _errorData: {"name":"fa5f25e3-Super-Pooper-Name-8-892a-770a6c6e2172","httpStatusCode":404,"headers":{"Strict-Transport-Security":"max-age=31536000; includeSubDomains","Request-Context":"appId=cid-v1:d22e8498-MySuperApp-b65b9efeb1ed","x-ms-request-id":":0096e733-MySuperREquEsT-efca2a772cf9","x-ms-ratelimit-remaining-subscription-reads":"11999","x-ms-correlation-request-id":"006b54e9-4ef1blah-blah-be-blub75f276","x-ms-routing-request-id":"CANADACENTRAL:20220802T083113Z:c57f0ba8-cbde-4904-9941-dd11a5d52696","X-Content-Type-Options":"nosniff","Cache-Control":"private","Date":"Tue, 02 Aug 2022 08:31:13 GMT","ETag":"\"1D8A64673EC09C0\"","Server":"Microsoft-IIS/10.0","X-AspNet-Version":"4.0.30319","X-Powered-By":"ASP.NET"},"content":{"error":{"code":"WorkflowNotFound","message":"The workflow 'mysuperWorkF' could not be found."}},"contentLength":95}
_sourceErrorLevel: undefined
baseTypes: ["MsPortalFx.Errors.Error"]
code: undefined
data: {"operation":"ListWorkflowTriggerHistoriesByUri","uri":"https://management.azure.com/subscriptions/ab603228-MY-SUPER-SUBSCRIPTON/resourceGroups/MYSUPERRESOURCEGROUP/providers/Microsoft.Web/sites/MySuperSite/hostruntime/runtime/webhooks/workflow/api/management/workflows/mysuperWorkF/triggers/When_there_are_messages_in_a_queue/histories?api-version=2018-11-01"}
errorData: {"name":"fa5f25e3-ed98-45f8-892a-770a6c6e2172","httpStatusCode":404,"headers":{"Strict-Transport-Security":"max-age=31536000; includeSubDomains","Request-Context":"appId=cid-v1:d22e8498-1999-4f62-bd17-b65b9efeb1ed","x-ms-request-id":":0096e733-a438-43ff-bd61-efca2a772cf9","x-ms-ratelimit-remaining-subscription-reads":"11999","x-ms-correlation-request-id":"006b54e9-4ef1-464b-8325-d471be75f276","x-ms-routing-request-id":"CANADACENTRAL:20220802T083113Z:c57f0ba8-cbde-4904-9941-dd11a5d52696","X-Content-Type-Options":"nosniff","Cache-Control":"private","Date":"Tue, 02 Aug 2022 08:31:13 GMT","ETag":"\"1D8A64673EC09C0\"","Server":"Microsoft-IIS/10.0","X-AspNet-Version":"4.0.30319","X-Powered-By":"ASP.NET"},"content":{"error":{"code":"WorkflowNotFound","message":"The workflow 'mysuperWorkF' could not be found."}},"contentLength":95}
errorLevel: 2
extension: Microsoft_Azure_EMA
handled: undefined
innerErrors: []
message: Failed to get workflow triggers: error null or undefined
name: Error
source: Ema.Client.codeless
stack: Error: Failed to get workflow triggers: error null or undefined
    at new t (https://portal.azure.com/Content/Dynamic/ImvqABKxoeaS.js:73:895)
    at u (https://afd.hosting.portal.azure.net/ema/Content/Dynamic/75PDTILQZtf1.js:7:564)
    at Object.f [as logError] (https://afd.hosting.portal.azure.net/ema/Content/Dynamic/75PDTILQZtf1.js:7:122)
    at https://afd.hosting.portal.azure.net/ema/Content/Dynamic/1kgl0ySWkE6c.js:7:19521
timestamp: 4539897.899999976
type: MsPortalFx.Errors.Error
</pre>

**Comment by klawrawkz** [comment]
Anybody out there?? 
...
...
_At least we've still got Bowie:_
...
> For here
> Am I sitting in a tin can
> Far above the world
> Planet Earth is blue
> And there's nothing I can do
> Though I'm past one hundred thousand miles
> I'm feeling very still
> And I think my spaceship knows which way to go
> Tell my wife I love her very much she knows
...
> Ground Control to MLAT (Microsoft Logic App Team @Bec-Lyons, @MattFarm, etc.) 
> Your circuit's dead, there's something wrong
> Can you hear me, MLAT?
> Can you hear me, MLAT?
> Can you hear me, MLAT?
> Can you...

So on and so forth....

klaw
