### ISSUE TITLE
Logic App custom built-in connectors deployment

### ISSUE THREAD

**Issue by LSchuster** [Azure/logicapps#711]
### Describe the Bug

We have created a custom built-in connectors following this documentation https://learn.microsoft.com/en-us/azure/logic-apps/create-custom-built-in-connector-standard and a few other examples.

Locally the Logic App can be debugged in VS Code and the custom actions are working correctly.
![image](https://user-images.githubusercontent.com/15693320/215099183-a8691c06-ccb8-4ece-8ad0-abb1f07e9902.png)

But when we deploy the Logic App project we cant find the actions in the logic app designer and when we deploy a workflow using that action it is not displayed correctly.
![image](https://user-images.githubusercontent.com/15693320/215099502-9a51b964-ee37-42dd-99bf-1c25a33e940a.png)

We already have checked the files deployed to the Logic App using Kudu. There we can see that the dll containing the IExtensionConfigProvider, IServiceOperationsProvider and custom startup is present, as well as the  extensions.json containing the reference to the dll and its startup class.
`[assembly: Microsoft.Azure.WebJobs.Hosting.WebJobsStartup(typeof(qbq.Hamburg.LogicApp.Extensions.MLLP.MLLPStartup))]
namespace qbq.Hamburg.LogicApp.Extensions.MLLP
{
    using Microsoft.Azure.WebJobs;
    using Microsoft.Azure.WebJobs.Hosting;
    using Microsoft.Extensions.DependencyInjection.Extensions;

    public class MLLPStartup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            builder.AddExtension<MLLPServiceProvider>();
            builder.Services.TryAddSingleton<MLLPServiceOperationProvider>();            
        }
    }
}`
![image](https://user-images.githubusercontent.com/15693320/215100225-242c9475-4b50-4c28-b466-da37d5178d30.png)
![image](https://user-images.githubusercontent.com/15693320/215100236-e0a04798-c163-464b-83bc-c309cc898bef.png)
![image](https://user-images.githubusercontent.com/15693320/215100248-942edb48-52ba-44b0-95ed-12ee5c9415e4.png)

The only error i can find is the following
`Workflow Error: operationName='WorkflowDefinitionProvider.ProcessWorkflow', message='Workflow 'Stateful1' validate and create workflow operation failed, the exception is 'The value '/serviceProviders/MLLP' provided for the 'serviceProviderConfiguration.serviceProviderId' for 'Send_a_Message_to_a_MLLP_Service' is not valid.'', exception='Microsoft.Azure.Workflows.Common.ErrorResponses.ErrorResponseMessageException: The value '/serviceProviders/MLLP' provided for the 'serviceProviderConfiguration.serviceProviderId' for 'Send_a_Message_to_a_MLLP_Service' is not valid.
   at Microsoft.Azure.Workflows.Data.Engines.EdgeFlowDefinitionValidationEngine.ValidateServiceProviderAction(String actionName, FlowTemplateAction action, InsensitiveDictionary`1 triggers)
   at Microsoft.Azure.Workflows.Data.Engines.EdgeFlowDefinitionValidationEngine.OnValidateFlowAction(FlowPropertiesDefinition definition, String flowName, String actionName, InsensitiveDictionary`1 parameterValues, FlowOperationConfiguration flowOperationConfiguration, Boolean hasOpenApiOperationInWorkflow, IntegrationAccount integrationAccount)
   at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlowActions(FlowPropertiesDefinition definition, InsensitiveDictionary`1 parameterValues, String flowName, IntegrationAccount integrationAccount)
   at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlowTemplate(FlowPropertiesDefinition definition, InsensitiveDictionary`1 templateParameters, String flowName, IntegrationAccount integrationAccount, InsensitiveDictionary`1 appSettings)
   at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlow(String flowName, Flow existingFlow, FlowPropertiesDefinition definition, IntegrationAccount integrationAccount, InsensitiveDictionary`1 appSettings)
   at Microsoft.Azure.Workflows.Web.Engines.EdgeFlowWebManagementEngine.ValidateAndCreateFlow(String flowName, FlowPropertiesDefinition flowPropertiesDefinition)
   at Microsoft.WindowsAzure.ResourceStack.Common.Algorithms.AsyncRetry.Retry(Func`1 action, Int32 retryCount, TimeSpan retryInterval, CancellationToken cancellationToken, Nullable`1 retryTimeout, Func`2 isRetryable, Action`1 errorAction, Func`2 retryAfter)
   at Microsoft.Azure.Workflows.WebJobs.Extensions.Initialization.WorkflowFunctionDefinitionProvider.ProcessWorkflow(FlowFunction flowFunction, ConcurrentDictionary`2 flowsProcessed)', extensionVersion='1.3.7.0', siteName='mllp-on-azure-builtin-la', slotName='Production', activityId='ce37dbbf-4dd6-4ec5-8290-4096ef3a799a'.
`

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Follow Documentation: https://learn.microsoft.com/en-us/azure/logic-apps/create-custom-built-in-connector-standard
2. Upload created package to nuget.org
3. Convert Logic App project to nuget based project
4. Reference Nuget package in Logic App project
5. Deploy Logic App project to Standard Logic App deployed in Azure

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Initialize_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "Name",
                            "type": "string",
                            "value": "Lukas"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            },
            "Response": {
                "inputs": {
                    "body": {
                        "status": "yes"
                    },
                    "statusCode": 200
                },
                "kind": "http",
                "runAfter": {
                    "Send_a_Message_to_a_MLLP_Service": [
                        "Succeeded"
                    ]
                },
                "type": "Response"
            },
            "Send_a_Message_to_a_MLLP_Service": {
                "inputs": {
                    "parameters": {
                        "content": "asdasd",
                        "topic": "asdasd"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "MLLP",
                        "operationId": "WriteMessage",
                        "serviceProviderId": "/serviceProviders/MLLP"
                    }
                },
                "runAfter": {
                    "Initialize_variable": [
                        "Succeeded"
                    ]
                },
                "type": "ServiceProvider"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "manual": {
                "inputs": {
                    "method": "GET"
                },
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

**Comment by timjansenortec** [comment]
I also have a setup with a custom connector for Logic Apps Standard. This is working OK for me.

Do you maybe still have the setting in the logic app that indicates to use the 'standard' extension bundle?
setting AzureFunctionsJobHost__extensionBundle__version

**Comment by LSchuster** [comment]
Hey [timjansenortec](https://github.com/timjansenortec), thats exactly what i was doing wrong, i have deployed the same project to a new logic app standard and it worked.

But now i have the problem that i cant see the run information. 
![image](https://user-images.githubusercontent.com/15693320/215540893-f348e21c-82a4-4535-8c25-4f6e0ba4c536.png)
The action does everything and is also giving outputs to the Response, but i cannot get any information about the run of this action.

Did you also enounter this problem?

**Comment by timjansenortec** [comment]
I can see the Inputs+Outputs of my custom connector just fine.
Not sure what could be the issue...did you specify the Inputs+Outputs on the custom connector schema?

**Comment by LSchuster** [comment]
I did it like in this repository https://github.com/Baran121/KafkaExt/tree/main/Providers in the WriteMessageApiOperationManifest.cs

**Comment by timjansenortec** [comment]
The example in that repository looks OK. 
I don't know what the issue could be then.

**Comment by kritollm** [comment]
I had exactly the same problem. All the examples I've seen from Microsoft, as well as the example you used have an RGBA value for BrandColor. The weird thing is that the designer doesn't support RGBA, only RGB. The Javascript code crashes, that's why you can't see the result.

4287090426 = 0xFF87CEFA. So if you change to something like this, you can see the result: BrandColor = 0xcccccc

![ToHexThrow](https://user-images.githubusercontent.com/12444201/218304124-2cd13bc2-8ae0-4144-94ba-a8c3e000d139.png)
