### ISSUE TITLE
VS Code_SQL Action: Before adding long running scenario query, the workflow is failed but there are error logs in terminal.

### ISSUE THREAD

**Issue by vgouth** [Azure/logicapps#902]
### Describe the Bug

Before adding long running scenario query, the workflow is failed but there are error logs in terminal.

### Plan Type

Standard (VS code)

### Steps to Reproduce the Bug or Issue

1.Create a project and add Stateful workflow in VS code.
2.Convert your workflow in SQL Based and Nuget Based.
3.Open Designer and add http trigger and sql_Execute query_EXEC wait2;
4.Save and Debug the workflow.

**Expected:** The workflow should be failed after 2 minutes.

**Actual:** The workflow is failed after 2 minutes but there are error logs present in terminal.

### Screenshots or Videos

![image](https://github.com/Azure/logicapps/assets/113517384/82018ace-d191-42b6-9099-97a901e7f76a)

**Error message in terminal:**

[2023-10-18T13:41:43.354Z] Error message: correlationId='ae091658-ad43-4f2f-b9fe-64931d26b338', operationName='sql.SqlServiceOperationsProvider.ExecuteQueryAsync', message='A severe error occurred on the current command. The results, if any, should be discarded.
[2023-10-18T13:41:43.355Z] Operation cancelled by user.', exception='Microsoft.Data.SqlClient.SqlException (0x80131904): A severe error occurred on the current command. The results, if any, should be discarded.
[2023-10-18T13:41:43.356Z] Operation cancelled by user.
[2023-10-18T13:41:43.357Z] at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction) [2023-10-18T13:41:43.358Z]    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
[2023-10-18T13:41:43.358Z] at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
[2023-10-18T13:41:43.359Z] at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
[2023-10-18T13:41:43.360Z] at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
[2023-10-18T13:41:43.361Z] at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
[2023-10-18T13:41:43.362Z] at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
[2023-10-18T13:41:43.365Z] at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
[2023-10-18T13:41:43.367Z] at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
[2023-10-18T13:41:43.368Z] at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
[2023-10-18T13:41:43.369Z] at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
[2023-10-18T13:41:43.371Z] at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
[2023-10-18T13:41:43.372Z] --- End of stack trace from previous location ---
[2023-10-18T13:41:43.373Z] at Microsoft.Azure.Workflows.ServiceProviders.Sql.Utilities.SqlExecutor.GetSqlDataReader(SqlCommand command, CommandBehavior commandBehavior, CancellationToken cancellationToken)
[2023-10-18T13:41:43.373Z] at Microsoft.Azure.Workflows.ServiceProviders.Sql.Utilities.SqlExecutor.ExecuteQueryAndGetResult(SqlCommand command, CommandBehavior commandBehavior, CancellationToken cancellationToken, String callerName)
[2023-10-18T13:41:43.374Z] at Microsoft.Azure.Workflows.ServiceProviders.Sql.Utilities.SqlExecutor.ExecuteQueryAsync(ConnectionProperties connectionProperties, IDictionary`2 queryParameters, String query, CommandBehavior commandBehavior)
[2023-10-18T13:41:43.375Z] ClientConnectionId:3a204b1d-2cf4-4511-817b-ac082dbec2fd', organizationId='', activityVector='IN.03', additionalProperties='{"ParentActivityId":"00-21c16d5a7735661095bb3ddd707d3f49-581b3b61829e3115-00"}', extensionVersion='1.44.1.0', siteName='UNDEFINED_SITE_NAME', slotName='', activityId='b154c40d-a808-45cf-97ed-906ce7b26c74'.
[2023-10-18T13:41:43.437Z] Executed 'Functions.WorkflowDispatcher' (Succeeded, Id=131fff88-8bb6-404a-8a31-5fab02426731, Duration=120475ms)

### Additional context

There are error logs in the terminal. Is the error logs expected?

Error logs repro in SQL and nuget artifact but not in bundle artifact

**VSIX**- 2.72.1

AB#25531829

**Comment by vgouth** [comment]
@AbodeSaafan . As informed, closing this bug as per design.
