### ISSUE TITLE
Cannot read properties of undefined (reading 'credentials2')

### ISSUE THREAD

**Issue by AkunerTulachan** [Azure/logicapps#991]
### Describe the Bug

Hi 
Having issue opening a designer for logic app standard on Visual studio code once I sign in to Azure.

3:30:46 PM: Error: Cannot read properties of undefined (reading 'credentials2')

Can someone please advise?

### Plan Type

standard

### Steps to Reproduce the Bug or Issue

![image](https://github.com/Azure/logicapps/assets/55730006/7862bffe-c129-4384-b49d-92cc0e73ef93)

AB#26916514

**Comment by ccastrotrejo** [comment]
Hi @AkunerTulachan thanks for raising this issue. Is this still happening? This kind of issue happens when something goes wrong with the sign-in in Azure. 
Could you please update the extension to the latest version and try again?

Is this issue is still happening I will take a further look

**Comment by steven-keller** [comment]
I just got this error message while trying to sign in to AzureUSGovernment.    Turns out I needed to go into the Azure Extension settings and specify AzureUSGovernment in the "Cloud" setting to get it to work.  Hopefully this helps someone.

**Comment by ccastrotrejo** [comment]
Hey @steven-keller thanks for letting us know, I will check that scenario. Although it does makes sense that you need to specify the cloud you are trying to sign in to be able to get the right credentials.

@AkunerTulachan is this the case for your issue? Are you trying to sign in to a different cloud?

<img width="831" alt="image" src="https://github.com/Azure/logicapps/assets/102700317/83ab9961-53cc-4669-abc6-7c880fad6e0a">

**Comment by matthieupetite** [comment]
Hi there still having the same issue here even if the AzureCloud Option is set :(

**Comment by ccastrotrejo** [comment]
Hi @matthieupetite could you please try to sign in using the following command from the command palette? Please make sure is the command azure-account.login
<img width="649" alt="327896426-5edad9b0-8ea1-4d04-8da9-a7d6823341af" src="https://github.com/user-attachments/assets/1bb7346c-2a8a-407c-9a72-47dc8159b605">

**Comment by ms-86** [comment]
I have the same error. I have no problem signing in with Azure: Sign In azure-account.login - after doing that I have a new tab opened in my web browser and after using my credentials I'm getting this:

![image](https://github.com/user-attachments/assets/da0d345e-1b33-45b8-91c7-e6363cfa913a)

I can also browse through different subscriptions:

![image](https://github.com/user-attachments/assets/d5b51213-24ac-465a-90be-3011feab3bc6)

Please be aware that using my user account I can switch between 3 different tenants and that's why I have set Azure: Tenant property in Azure Account extension settings:

![image](https://github.com/user-attachments/assets/f62ccc82-f99a-41ff-810e-afc66157e8e4)

<details><summary>Output of the Azure Logic Apps (Standard)</summary>
<p>
1:20:45 PM: Starting Design Time Api
1:20:45 PM: Running command: "func host start --port 8001" with pid: "27776"...

Azure Functions Core Tools
Core Tools Version:       4.0.6280 Commit hash: N/A +421f0144b42047aa289ce691dc6db4fc8b6143e6 (64-bit)
Function Runtime Version: 4.834.3.22875


Functions:

	NetFxLanguageWorkerFunction: NetFxTrigger

	XsltNetFxLanguageWorkerFunction: NetFxTrigger

For detailed output, run func with --verbose flag.
[2024-10-02T11:20:48.463Z] Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1727868048.436000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3151,"referenced_errors":[{"created":"@1727868048.436000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")
[2024-10-02T11:20:48.464Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:20:48.464Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2024-10-02T11:20:48.464Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.<SendStartStreamMessageAsync>d__13.MoveNext() in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 88
[2024-10-02T11:20:48.464Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:20:48.464Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:20:48.464Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2024-10-02T11:20:48.464Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.<StartAsync>d__11.MoveNext() in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 67
[2024-10-02T11:20:48.464Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:20:48.464Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:20:48.464Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2024-10-02T11:20:48.464Z]    at Microsoft.Azure.Functions.Worker.WorkerHostedService.<StartAsync>d__3.MoveNext() in D:\a\_work\1\s\src\DotNetWorker.Core\WorkerHostedService.cs:line 27
[2024-10-02T11:20:48.465Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:20:48.465Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:20:48.465Z]    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
[2024-10-02T11:20:48.465Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:20:48.465Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:20:48.465Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2024-10-02T11:20:48.465Z]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
[2024-10-02T11:20:48.465Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:20:48.465Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:20:48.465Z]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
[2024-10-02T11:20:48.465Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:20:48.465Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:20:48.465Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2024-10-02T11:20:48.465Z]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
[2024-10-02T11:20:48.465Z]    at Microsoft.Azure.Workflows.Functions.NetFxWorker.Program.Main(String[] args) in C:\__w\1\s\src\functionWorkers\Flow.Functions.NetFxWorker\Program.cs:line 34
[2024-10-02T11:20:48.470Z] Language Worker Process exited. Pid=9624.
[2024-10-02T11:20:48.470Z] C:\Users\myusername\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.87.34\NetFxWorker\Microsoft.Azure.Workflows.Functions.NetFxWorker.exe exited with code -532462766 (0xE0434352). Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1727868048.436000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3151,"referenced_errors":[{"created":"@1727868048.436000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}").
1:20:50 PM: Error: Cannot read properties of undefined (reading 'credentials2')
[2024-10-02T11:20:52.835Z] Host lock lease acquired by instance ID '00000000000000000000000085471C89'.
[2024-10-02T11:21:47.866Z] Starting worker process failed
[2024-10-02T11:21:47.866Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
[2024-10-02T11:21:47.870Z] Failed to start a new language worker for runtime: node.
[2024-10-02T11:21:47.870Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
1:23:16 PM: Stopping Design Time Api
1:23:16 PM: Starting Design Time Api
1:23:16 PM: Running command: "func host start --port 8000" with pid: "41504"...

Azure Functions Core Tools
Core Tools Version:       4.0.6280 Commit hash: N/A +421f0144b42047aa289ce691dc6db4fc8b6143e6 (64-bit)
Function Runtime Version: 4.834.3.22875


Functions:

	NetFxLanguageWorkerFunction: NetFxTrigger

	XsltNetFxLanguageWorkerFunction: NetFxTrigger

For detailed output, run func with --verbose flag.
[2024-10-02T11:23:19.796Z] Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1727868199.765000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3151,"referenced_errors":[{"created":"@1727868199.765000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")
[2024-10-02T11:23:19.796Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:23:19.796Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2024-10-02T11:23:19.796Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.<SendStartStreamMessageAsync>d__13.MoveNext() in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 88
[2024-10-02T11:23:19.797Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:23:19.797Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:23:19.797Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2024-10-02T11:23:19.797Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.<StartAsync>d__11.MoveNext() in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 67
[2024-10-02T11:23:19.797Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:23:19.797Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:23:19.797Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2024-10-02T11:23:19.797Z]    at Microsoft.Azure.Functions.Worker.WorkerHostedService.<StartAsync>d__3.MoveNext() in D:\a\_work\1\s\src\DotNetWorker.Core\WorkerHostedService.cs:line 27
[2024-10-02T11:23:19.797Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:23:19.797Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:23:19.798Z]    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
[2024-10-02T11:23:19.798Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:23:19.798Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:23:19.798Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2024-10-02T11:23:19.798Z]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
[2024-10-02T11:23:19.798Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:23:19.798Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:23:19.799Z]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
[2024-10-02T11:23:19.799Z] --- End of stack trace from previous location where exception was thrown ---
[2024-10-02T11:23:19.799Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2024-10-02T11:23:19.799Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[2024-10-02T11:23:19.799Z]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
[2024-10-02T11:23:19.799Z]    at Microsoft.Azure.Workflows.Functions.NetFxWorker.Program.Main(String[] args) in C:\__w\1\s\src\functionWorkers\Flow.Functions.NetFxWorker\Program.cs:line 34
[2024-10-02T11:23:19.802Z] Language Worker Process exited. Pid=41136.
[2024-10-02T11:23:19.802Z] C:\Users\myusername\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.87.34\NetFxWorker\Microsoft.Azure.Workflows.Functions.NetFxWorker.exe exited with code -532462766 (0xE0434352). Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1727868199.765000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3151,"referenced_errors":[{"created":"@1727868199.765000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}").
[2024-10-02T11:23:24.199Z] Host lock lease acquired by instance ID '00000000000000000000000085471C89'.
[2024-10-02T11:24:19.238Z] Starting worker process failed
[2024-10-02T11:24:19.238Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
[2024-10-02T11:24:19.242Z] Failed to start a new language worker for runtime: node.
[2024-10-02T11:24:19.242Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.


</p>
</details>
